CREATE DATABASE DBMS;
SHOW databases;
USE DBMS;
CREATE TABLE STUDENT(
         
         REG_NO INT(3),
         NAME VARCHAR(30),
         gender enum('m','f'),
         DOB INT(10),
         MOBILENO   INT(10),
         CITY VARCHAR(20)

);
DESCRIBE STUDENT;
ALTER TABLE STUDENT
ADD COLUMN STD_ID INT auto_increment PRIMARY KEY;
CREATE TABLE FACULTY(
             FACNO INT,
             FACT_NAME VARCHAR(20),
             DOB datetime(6),
             DOJ datetime,
             MOBILE_NO  INT(10)
);
DESCRIBE FACULTY;
CREATE TABLE DEPARTMENT(
           DEPARTMENT_NO INT,
           DEP_NAME VARCHAR(20),
           DEP_HEAD VARCHAR(10)


);
DESCRIBE DEPARTMENT;
CREATE TABLE COURSE(
         COURSE_NO INT,
         COURSE_DES VARCHAR(30),
         CORSE_TYPE   CHAR(4),
         SEM_NO INT,
         HALL_NO INT,
         FACNO INT


);
DESCRIBE COURSE;
ALTER TABLE FACULTY
ADD PRIMARY KEY (FACNO);
INSERT INTO STUDENT (REG_NO,NAME,gender,DOB,MOBILENO,CITY)
values (192111620,'ABHINAV','F',19082004,9849161897,'KVZ'),(192111130,'ADITYA','F',19082003, NULL,'WEST GODAVARI'),(192111595,'MANI','M',21102003,635194321,'KAKINADA') ;
SELECT*FROM STUDENT;
ALTER TABLE STUDENT
drop COLUMN DOB; 
